blog/urls.py
from django.conf.urls import url
from . import views

app_name = "blog"

urlpatterns = [
    url(r'^$',views.PostListView.as_view(),name="post_list"), #HOme page
    url(r'^about/$', views.AboutView.as_view(), name="about"),  #This is the index page
    url(r'^post/detail/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name="post_detail"), #DOMAIN/detail/pk/
    url(r'^post/new/$', views.PostCreateView.as_view(), name="post_new"), #DOMAIN/post/new/
    url(r'^post/update/(?P<pk>\d+)/$', views.PostUpdateView.as_view(), name="post_update"),
    url(r'^post/delete/(?P<pk>\d+)/$', views.PostDeleteView.as_view(), name="post_delete"),
    url(r'^draft/$',views.DraftListView.as_view(),name="draft_list"),
    url(r'^post/comment/(?P<pk>\d+)/$', views.add_comment_to_post, name="add_comment_to_post"),
    url(r'^post/comment/approve/(?P<pk>\d+)/$', views.comment_approve, name="comment_approve"),
    url(r'^post/comment/delete/(?P<pk>\d+)/$', views.comment_remove, name="comment_remove"),
    url(r'^post/publish/(?P<pk>\d+)/$', views.post_publish, name="post_publish"),
]

mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views   #FOr built-in login and logout


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('blog.urls')),   #Anything that is not Domain/admin goto blog.urls
    url(r'^accounts/login/$', views.login, name="login"),   #I didn't do shit to hook it up with registration/login.html
    url(r'^accounts/logout/$', views.logout, name="logout", kwargs={'next_page':'/'}),  #it redirects to DOMAIN/
]

blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default = timezone.now())
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()  #To commit it to the database


    def approve_comments(self):  #returns the comments which are approved by the admin
        return self.comments.filter(approved_comment = True)


    def __str__(self):
        return self.title



class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now())
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()


    def __str__(self):
        return self.text

blog/forms.py
from blog.models import Post, Comment
from django import forms


class PostForm(forms.ModelForm):

    class Meta():
        model = Post
        fields = ['author', 'title', 'text']

        widgets = {  #inserting css classes
        'title':forms.TextInput(attrs={'class':'textinputclass'}),
        'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})
        }


class CommentForm(forms.ModelForm):

    class Meta():
        model = Comment
        fields = ['author','text']


        widgets = {
        'author':forms.TextInput(attrs={'class':'textinputclass'}),
        'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea'})
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect  #(instead of redirect u may use HttpResponseRedirect If you want :)
from django.utils import timezone
from blog.models import Post, Comment
from blog.forms import PostForm, CommentForm
from django.utils import timezone
from django.contrib.auth.decorators import login_required #this decorator ONLY for functions !!
from django.contrib.auth.mixins import LoginRequiredMixin #use this Mix-in in classes
from django.core.urlresolvers import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

# Create your views here.
class AboutView(TemplateView):
    template_name = "blog/about.html"

class PostListView(ListView):
    model = Post
    template_name = "blog/post_list.html"
    context_object_name = "posts"


    #now this ListView "mysteriously" passes all stuff to .htnl in object named posts what if we wanna put some condition
    #as to which objects to give to us? for that we OVERRIDE get_queryset()
    def get_queryset(self):
        return Post.objects.filter(published_date__lte = timezone.now()).orderby("-published_date")
        # default would have been Post.objects.all() notice in orderby I passed a negative sign for DESCENDING
        #else OLDER posts would have come first

class PostDetailView(DetailView):
    model = Post
    template_name = "blog/post_detail.html"
    context_object_name = "post_detail"


class PostCreateView(LoginRequiredMixin, CreateView):
    login_url = "/login/"  #In case the person is not logged where should they go?
    redirect_field_name = "blog/post_form.html"  #After logging in redirect here
    form_class = PostForm  #Remember this guy passes its own object named form which has trivial stuff if you wanna send your own form then OVERRIDE
    context_object_name = "form"  #now it sends PostForm in object name of form

    model = Post
    fields = "__all__"
    template_name = "blog/post_form.html"


class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = "/login/"  #In case the person is not logged where should they go?
    redirect_field_name = "blog/post_detail.html"
    form_class = PostForm  #Remember this guy passes its own object named form which has trivial stuff if you wanna send your own form then OVERRIDE
    context_object_name = "form"  #now it sends PostForm in object name of form

    model = Post
    fields = ["author","title","text"]
    template_name = "blog/create_post.html"


class PostDeleteView(LoginRequiredMixin, DeleteView):
    login_url = "/login/"  #In case the person is not logged where should they go?
    redirect_field_name = "blog/post_detail.html"
    model = Post
    success_url = reverse_lazy("blog:post_list")
    template_name = "blog/post_confirm_delete.html"
    context_object_name = "post"


class DraftListView(LoginRequiredMixin, ListView):
    login_url = "/login/"  #In case the person is not logged where should they go?
    redirect_field_name = "blog/post_detail.html"
    model = Post
    template_name = "blog/post_draft_list.html"
    context_object_name = "posts"

    def get_queryset(self):
        return Post.object.filter(published_date__isnull = True).orderby('-create_date')

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('post_detail', pk=post.pk)  #lol or simply pk=pk (its passed already hehe)



########################################
########################################

@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()
        return render(request, 'blog/comment_form.html', {"form":form})


@login_required   #Decorators are love <3
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()  #I have a built-in function
    return redirect('post_detail', pk=comment.post.pk)  #alt is HttpResponseRedirect(reverse()) this is amazing LOL

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('post_detail', pk=post_pk)

blog/templates/blog/about.html
{%extends "blog/base.html"%}

{%block title%}About{%endblock%}



{%block body%}

  <div class="jumbotron">
    <h2 class="display-2">About Me</h2>
    <p>My name is <em>Dipankar Shrivastava</em> and I made this blog, Kudos!</p>

{%endblock%}

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'css/blog.css' %}" type="text/css">
  <!-- Custom Font -->
  <link href="https://fonts.googleapis.com/css?family=Russo+One" rel="stylesheet">
  <title>{% block title %}BASE{% endblock %}</title>
</head>

<body>

  <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top" style="margin-bottom:100px;">
    <div class="container">
      <a href="{% url 'blog:post_list' %}" class="navbar-brand">TweakLAB</a>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#myNav"><span class="navbar-toggler-icon"></span></button>
      <div id="myNav" class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a href="{% url 'blog:about' %}" class="nav-link">About</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'blog:post_new' %}" class="nav-link">New Post</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'blog:draft_list' %}" class="nav-link">Drafts</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'logout' %}" class="nav-link">Logout</a>
            </li>
            <li class="nav-item">
              <a href="#" class="text-capitalize">Welcome: {{user.username}}</a>
            </li>
          {%else%}
          <li class="nav-item">
            <a href="{% url 'login' %}" class="text-capitalize"><i class="fas fa-sign-in-alt"></i></a>
          </li>
          {% endif %}
        </ul>
    </div>
    </div>
  </nav>
  <div class="container content">
    <div class="row">
      <div class="col-md-8">
        <div class="blog_posts">
          {% block body %}

          {% endblock %}
      </div>
      </div>
    </div>
  </div>


  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
</body>

</html>

blog/templates/blog/comment_form.html
{%extends "blog/base.html"%}

{%block title%}About{%endblock%}



{%block body%}
  <div class="jumbotron">
    <h3 class="display-4">New Comment</h3>
    <form class="post-form" method="post">{%csrf_token%}
      {{ form.as_p }}
      <input type="submit" value="Comment" class="btn btn-primary">
    </form>

    <script>
      var editor = new MediumEditor(".editable") ; //Look over in forms.py you used the editable class which will use this medium editor functionality
    </script>
{%endblock%}

blog/templates/blog/post_confirm_delete.html
{%extends "blog/base.html"%}

{%block title%}Confirm Deletion{%endblock%}



{%block body%}
  <form method='POST'>{%csrf_token%}
    <p>Are you sure you want to delete: {{post}} ?</p>
    <input type="submit" value="Delete" class="btn btn-danger">
    <a href="{% url 'blog:post_detail' pk=post.pk %}" class="btn btn-info">Cancel</a> 
  </form>


{%endblock%}

blog/templates/blog/post_detail.html
{%extends "blog/base.html"%}

{%block title%}Post Details{%endblock%}



{%block body%}
  <h1 class="posttitle loader">{{post.title}}</h1>
  {% if post.published_date %}
    <div class="date postdate">
      {{post.published_date|date:"D M Y"}}
    </div>
  {% else %}
    <a class="btn btn-default" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
  {% endif %}
  <p class="postcontent">{{post.text|safe|linebreaks}}</p>
  {% if user.is_authenticated %}
    <a href="{% url 'blog:post_update' pk=post.pk %}" class="btn btn-info"><i class="far fa-edit"></i></a>
    <a href="{% url 'blog:post_delete' pk=post.pk %}" class="btn btn-danger"><i class="fas fa-trash-alt"></i></a>
  {% endif %}

  <a href="{% url 'blog:add_comment_to_post' pk=post.pk %}" class="btn btn-priamry">Add Comment</a>

  <div class="container">
    {% for comment in post.comments.all %}
      {% if user.is_authenticated or comment.approved_comment %}
        {{comment.create_date}}
        {% if not comment.approved_comment %}
          <a href="{% url 'blog:comment_remove' pk=post.pk %}" class="btn btn-secondary"><i class="far fa-edit"></i></a>
          <a href="{% url 'blog:comment_approve' pk=post.pk %}" class="btn btn-danger">Approve</a>
        {%endif%}
        <p>{{comment.text|safe|linebreaks}}</p>
        <p>Posted by: {{comment.author}}</p>
      {%endif%}
      {%empty%} <!-- If post.comment.all is EMPTY -->
        <p>No Comments to Show</p>
    {% endfor %}
  </div>

{%endblock%}

blog/templates/blog/post_draft_list.html
{%extends "blog/base.html"%}

{%block title%}Post Drafts{%endblock%}



{%block body%}
  {% for post in posts %}
    <div class="post">
      <p class="date">Created: {{post.create_date|date:"d-m-Y"}}</p>
      <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a></h1>
      <p>{{post.text|truncatechars:200}}</p>
    </div>
  {%endfor%}


{%endblock%}

blog/templates/blog/post_form.html
{%extends "blog/base.html"%}

{%block title%}New Post{%endblock%}



{%block body%}
  <div class="jumbotron">
    <h2 class="display-3">Create New Post:</h2>
    <form method="POST">{%csrf_token%}
      {{form.as_p}}
      <button type="submit" class="btn btn-primary">Create Post</button>
    </form>
  </div>

  <script>
    var editor = new MediumEditor('.editable');   // Look over in forms.py you used the editable class which will use this medium editor functionality
  </script>

{%endblock%}

blog/templates/blog/post_list.html
{%extends "blog/base.html"%}

{%block title%}Posts{%endblock%}



{%block body%}
  <div class="centerstage">
    {% for post in posts %}
      <div class="post">
        <h1 class="display-4 text-capitalize"><a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a></h1>
        <div class="date">
          <p class="text-muted">Published on:{{post.published_date|date:"D M Y"}}</p>
        </div>
        <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{post.approve_comments.count}}</a>
      </div>
    {% endfor %}
  </div>

{%endblock%}